
[build]
  command = "npm run build"
  publish = "out" # Next.js static export directory

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
