// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  "apiKey": "API_KEY",
  "authDomain": "AUTH_DOMAIN",
  "projectId": "PROJECT_ID",
  "storageBucket": "STORAGE_BUCKET",
  "messagingSenderId": "MESSAGING_SENDER_ID",
  "appId": "APP_ID",
  "measurementId": "MEASUREMENT_ID"
};
